version: '3.9'

services:
    postgres-db:
        container_name: gcommerce
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: database
        ports:
            - '5432:5432'
