# fly.toml app configuration file generated for gcommerce-api on 2023-05-29T14:43:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gcommerce-api"
primary_region = "gig"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
